In [24]:
import numpy as np
import cv2


# Q1: implement a linear regression model
data row1 > header 
 ### 1: data preprocessing 
       #i. apply to_add array to data where element 1 added to row 1 , element 2 added to row 2 and so on 
       #ii.apply to_Mult array to the data row by to 
 ### 2: get the prediction values using the hyposis function weight array (regression_model)

In [25]:
Data= np.array([[1000,1001,1002,1003],
                [8,18,28,38],
               [16,26,36,46],
               [4,14,24,44]],dtype="int64")

to_add = np.array([2,4,6])
to_mult = np.array([10,100,1000,1000])
regression_model = np.array([2,4,6,8])

In [26]:
##step1 print dataset without header row
OnlyData = Data[1:,:]
print(OnlyData)

[[ 8 18 28 38]
 [16 26 36 46]
 [ 4 14 24 44]]


In [27]:
###step2 i. to_Add
add = OnlyData + np.reshape(to_add , (3,1))
print(add)

[[10 20 30 40]
 [20 30 40 50]
 [10 20 30 50]]


In [28]:
##step3 ii. to_MUlt
after_mult  = to_mult * add[:, np.newaxis]
after_mult

array([[[  100,  2000, 30000, 40000]],

       [[  200,  3000, 40000, 50000]],

       [[  100,  2000, 30000, 50000]]], dtype=int64)

In [29]:
###step4 prediction results
prediction = after_mult.dot(regression_model)
prediction

array([[508200],
       [652400],
       [588200]], dtype=int64)

# Q2. Transformation

### apply crop , rotation  to the image 

#1: convert image from  BGR scale to Gray , Red ,Green & Blue scale
#2: crop the right  half
#3: crop the right bottom quarter
#4: zoom in by remove the quarter border from all sides 
#5: flip on x-axis 
#6: flip on y-axis 

In [30]:
image=cv2.imread("image.jpg") ### in_BGR
cv2.imshow("original_image",image)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [31]:
## step1 print image data 
print( image)

[[[246 236 236]
  [247 237 237]
  [248 238 238]
  ...
  [250 242 235]
  [250 242 235]
  [250 242 235]]

 [[246 236 236]
  [246 236 236]
  [247 237 237]
  ...
  [249 241 234]
  [249 241 234]
  [249 241 234]]

 [[245 235 235]
  [246 236 236]
  [247 237 237]
  ...
  [249 241 234]
  [249 241 234]
  [249 241 234]]

 ...

 [[ 23  33  16]
  [ 44  54  37]
  [ 65  72  57]
  ...
  [ 19  61  68]
  [ 19  61  68]
  [ 19  61  68]]

 [[ 34  46  28]
  [ 57  69  51]
  [ 71  82  66]
  ...
  [ 11  60  70]
  [ 11  60  70]
  [ 11  60  70]]

 [[ 71  85  67]
  [ 94 108  90]
  [103 116 100]
  ...
  [ 10  64  75]
  [ 10  64  75]
  [ 10  64  75]]]


In [32]:
## step2 print image shape
image.shape

(183, 276, 3)

In [33]:
## step3  get the value of lx ,ly 

lx = image.shape[1]
ly = image.shape[0]
lx,ly

(276, 183)

In [34]:
### step4 image in gray scale 
grey = image[:,:,0]
cv2.imshow("Gray scale",grey)
cv2.waitKey(0)
cv2.destroyAllWindows()

BGR

In [35]:
blue = image.copy()
blue[:,:,1] =0
blue[:,:,2] =0
green = image.copy()
green[:,:,0] =0
green[:,:,2] =0
red = image.copy()
red[:,:,0] =0
red[:,:,1] =0

In [36]:
### step 5 image in Blue scale 
cv2.imshow("Blue Scale",blue)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [37]:
### step 6 image in red scale 

cv2.imshow("Red Scale",red)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [38]:
### step 7 image in Green scale 

cv2.imshow("Green scale",green)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [15]:
image.shape

(183, 276, 3)

In [16]:
# step 8 crop the right half
crop_right= image[:, int(image.shape[1]/2):]
cv2.imshow("original_image",image)
cv2.imshow(" right half",crop_right)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [28]:
## step 9 crop the right bottom quarter

right_bottom_quarter = image[(ly-int(image.shape[0]/2)):, (lx - int(image.shape[1]/2)):]
cv2.imshow("gray",grey)
cv2.imshow(" right bottom quarter",right_bottom_quarter)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [39]:
## step 10 remove the quarter border from all sides 

remove_the_quarter = image[int(ly/4):ly-(int(ly/4)),int(lx/4):lx-(int(lx/4))]
cv2.imshow("original_image",image)
cv2.imshow(" zoom in ",remove_the_quarter)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [40]:
## step 11 flip on x-axis 
flip_x = image[::-1, :, :]
cv2.imshow("original_image",image)
cv2.imshow(" flip the image in x axis ",flip_x)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [41]:
## step 12 flip on y-axis
flip_y = image[:, ::-1, :]
cv2.imshow("original_image",image)
cv2.imshow(" flip the image in y axis ",flip_y)
cv2.waitKey(0)
cv2.destroyAllWindows()

## Q3  Write a program to broadcast on different shapes of arrays where p(3,3) + q(3)

- p >> [[0, 0, 0],[1, 2, 3],[4, 5, 6]]
- q >> [10, 11, 12]

In [42]:
def broadcast(Arr1,Arr2):
    return Arr1 + Arr1
p = np.array( [[0, 0, 0],[1, 2, 3],[4, 5, 6]])
q = np.array([10, 11, 12])
broadcast(p,q)

array([[ 0,  0,  0],
       [ 2,  4,  6],
       [ 8, 10, 12]])

## Q4 Write a NumPy program to make an array immutable 

In [43]:
def array_immutable(Arr):
    Arr.flags.writeable = False
    return Arr
array_immutable(p)
p[0] = 1

ValueError: assignment destination is read-only

## Q5 Write a NumPy program to create a new array of 3*5, filled with 2

In [44]:
def Twoss(size):
    return np.ones(size) * 2
    
Twoss((3,5))

array([[2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.]])

## Q6 Write a NumPy program to get the number of nonzero elements in an array

- array = [[0, 10, 20], [20, 0, 40]]

In [45]:
def none_zeros(arr):
    return (arr != 0).sum()
array =  np.array([[0, 10, 20], [20, 0, 40]])
none_zeros(array)

4

## Q7 Write a NumPy program to get the minimum and maximum value of an array along the second axis

- create array 2x2 contains data from 0 to 3 

In [46]:
def Min_Max(Arr):
    return np.min(array2x2,axis =1 ) , np.max(array2x2,axis =1) 

array2x2 = np.arange(4).reshape(2,2)
Min_Max(array2x2)

(array([0, 2]), array([1, 3]))

## Q8  Write a NumPy program to compute the mean, median,standard deviation, and variance of a given array 

- array = [0 4 2 1 3 5]

In [47]:
def Compute(arr):
    print('mean', np.mean(arr))
    print('median', np.median(arr))
    print('std', np.std(arr))
    print('variance', np.var(arr))
array = [0 ,4 ,2, 1, 3, 5]
Compute(array)

mean 2.5
median 2.5
std 1.707825127659933
variance 2.9166666666666665
